/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProServicesRouteImport } from './routes/pro.services'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProCalendarRouteImport } from './routes/pro.calendar'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProServicesRoute = ProServicesRouteImport.update({
  id: '/pro/services',
  path: '/pro/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProCalendarRoute = ProCalendarRouteImport.update({
  id: '/pro/calendar',
  path: '/pro/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/pro/calendar': typeof ProCalendarRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/pro/calendar': typeof ProCalendarRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/pro/calendar': typeof ProCalendarRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/client/dashboard'
    | '/pro/calendar'
    | '/pro/dashboard'
    | '/pro/services'
    | '/provider/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/client/dashboard'
    | '/pro/calendar'
    | '/pro/dashboard'
    | '/pro/services'
    | '/provider/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/messages'
    | '/pricing'
    | '/search'
    | '/client/dashboard'
    | '/pro/calendar'
    | '/pro/dashboard'
    | '/pro/services'
    | '/provider/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRoute
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ProCalendarRoute: typeof ProCalendarRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProServicesRoute: typeof ProServicesRoute
  ProviderIdRoute: typeof ProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/services': {
      id: '/pro/services'
      path: '/pro/services'
      fullPath: '/pro/services'
      preLoaderRoute: typeof ProServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/calendar': {
      id: '/pro/calendar'
      path: '/pro/calendar'
      fullPath: '/pro/calendar'
      preLoaderRoute: typeof ProCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRoute,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ProCalendarRoute: ProCalendarRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProServicesRoute: ProServicesRoute,
  ProviderIdRoute: ProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
